const Cards = [
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/19021/mclaren-765lt-spider-2022-thumb.jpg',
        model: 2021,
        km: 53,
        city: 'زنجان',
        price: '45,000,000',
        names: 'عبدی',
        car: ' McLaren 765LT spider',
        special: true,
        key: false,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/bmw.jpg',
        count: 85,
    },
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/19017/ferrari-sf90-stradale-by-novitec-2021-thumb.jpg',
        model: 2010,
        km: 100,
        city: 'بابل',
        price: '5,000,000',
        names: 'احمدی',
        car: ' Ferrari SF90 ',
        special: false,
        key: true,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/bentley.jpg',
        count: 42,
    },
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/18999/ferrari-f8-tributo-by-novitec-n-largo-2021-thumb.jpg',
        model: 2015,
        km: 5000,
        city: 'سهرورد',
        price: '85,000,000',
        names: 'محمدی',
        car: ' Ferrari F8',
        special: true,
        key: false,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/alfa-romeo.jpg',
        count: 5,
    },
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/19011/aston-martin-valhalla-2022-thumb.jpg',
        model: 2000,
        km: 300,
        city: 'تهران',
        price: '555,000,000',
        names: 'سید',
        car: 'Porsche',
        special: false,
        key: true,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/abarth.jpg',
        count: 1,
    },
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/18962/rml-short-wheelbase-2022-thumb.jpg',
        model: 2020,
        km: 565,
        city: 'مازندران',
        price: '412,000,000',
        names: 'رضای',
        car: 'RML Short Wheelbase',
        special: true,
        key: false,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/ferrari.jpg',
        count: 4,
    },
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/18961/porsche-911-992-gt3-with-touring-package-2021-thumb.jpg',
        model: 2022,
        km: 64185,
        city: 'رشت',
        price: '445,000,000',
        names: 'خلجی',
        car: 'Aston Martin Valhalla',
        special: true,
        key: true,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/volkswagen.jpg',
        count: 8,
    },
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/19043/hyundai-kona-n-usa-version-2022-thumb.jpg',
        model: 2018,
        km: 64185,
        city: 'تبریز',
        price: '445,000,885',
        names: 'رستمی',
        car: 'Aston Martin Valhalla',
        special: true,
        key: true,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/koenigsegg.jpg',
        count: 15,
    },
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/19046/ford-bronco-riptide-concept-2021-thumb.jpg',
        model: 2019,
        km: 64185,
        city: 'اصفحان',
        price: '445,475,000',
        names: 'آقای',
        car: 'Aston Martin Valhalla',
        special: false,
        key: false,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/mercedes-benz.jpg',
        count: 5,
    },
    {
        img: 'https://www.mad4wheels.com/img/free-car-images/desktop/19044/hyundai-santa-fe-xrt-usa-version-2022-thumb.jpg',
        model: 2014,
        km: 64185,
        city: 'تهران',
        price: '445,120,000',
        names: 'فاطمی',
        car: 'Aston Martin Valhalla',
        special: false,
        key: false,
        avatar: 'https://www.mad4wheels.com/img/car-brand-logo/desktop/lamborghini.jpg',
        count: 10,
    },
];

export default Cards;
